<?xml version="1.0" encoding="utf-8"?><Database Name="spreadsheet1" Class="BenefitAdminDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=eazfrlbvkq.database.windows.net;Initial Catalog=spreadsheet1;User ID=adminSP" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="spreadsheet1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Activity" Member="Activities">
    <Type Name="Activity">
      <Column Name="ACTCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ACTDesc" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="SVCCode" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="ICF_Code" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Association Name="Activity_ConditionActivity" Member="ConditionActivities" ThisKey="ACTCode" OtherKey="ACTCode" Type="ConditionActivity" />
      <Association Name="Activity_Material" Member="Materials" ThisKey="ACTCode" OtherKey="ACTCode" Type="Material" />
      <Association Name="Activity_SubActivity" Member="SubActivities" ThisKey="ACTCode" OtherKey="ACTCode" Type="SubActivity" />
    </Type>
  </Table>
  <Table Name="dbo.WelfareCategory" Member="WelfareCategories">
    <Type Name="WelfareCategory">
      <Column Name="WelfareID" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WelfareDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityCost" Member="ActivityCosts">
    <Type Name="ActivityCost">
      <Column Name="ACTCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="LabourCost" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="MaterialCost" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="CC_Equipment" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="CC_Building" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="IndirectCost" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="ProposedCost" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="CurrentCost" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="UnitCost" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="ReferencedCostOrg" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="TimsStamp" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AID" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="FutureCost" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Annotation_ActivityCost" Member="Annotation" ThisKey="AID" OtherKey="AID" Type="Annotation" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Annotation" Member="Annotations">
    <Type Name="Annotation">
      <Column Name="AID" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AText" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="AnnotationID" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="Reference" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Association Name="Annotation_ActivityCost" Member="ActivityCosts" ThisKey="AID" OtherKey="AID" Type="ActivityCost" />
    </Type>
  </Table>
  <Table Name="dbo.Condition" Member="Conditions">
    <Type Name="Condition">
      <Column Name="ConditionCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ConditionDesc" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="Condition" Member="Condition1" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Association Name="Condition_ConditionActivity" Member="ConditionActivity" ThisKey="ConditionCode" OtherKey="ConditionCode" Type="ConditionActivity" Cardinality="One" />
      <Association Name="Condition_ConditionService" Member="ConditionService" ThisKey="ConditionCode" OtherKey="ConditionCode" Type="ConditionService" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.ConditionActivity" Member="ConditionActivities">
    <Type Name="ConditionActivity">
      <Column Name="ConditionCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ACTCode" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Association Name="Activity_ConditionActivity" Member="Activity" ThisKey="ACTCode" OtherKey="ACTCode" Type="Activity" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Condition_ConditionActivity" Member="Condition" ThisKey="ConditionCode" OtherKey="ConditionCode" Type="Condition" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ConditionService" Member="ConditionServices">
    <Type Name="ConditionService">
      <Column Name="ConditionCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SVCCODE" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Association Name="Condition_ConditionService" Member="Condition" ThisKey="ConditionCode" OtherKey="ConditionCode" Type="Condition" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DisabilityType" Member="DisabilityTypes">
    <Type Name="DisabilityType">
      <Column Name="DisabilityCode" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Material" Member="Materials">
    <Type Name="Material">
      <Column Name="MaterialCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaterialDesc" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="EstimatedPrice" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="RealPrice" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="ACTCode" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Association Name="Activity_Material" Member="Activity" ThisKey="ACTCode" OtherKey="ACTCode" Type="Activity" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Material_ACT" Member="Material_ACTs">
    <Type Name="Material_ACT">
      <Column Name="MaterialCode" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ACTCode" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Ministry" Member="Ministries">
    <Type Name="Ministry">
      <Column Name="MinistryCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MinistryName" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Association Name="Ministry_Organization" Member="Organizations" ThisKey="MinistryCode" OtherKey="MinistryCode" Type="Organization" />
    </Type>
  </Table>
  <Table Name="dbo.Organization" Member="Organizations">
    <Type Name="Organization">
      <Column Name="OrgCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrgName" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="MinistryCode" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Association Name="Organization_Provider" Member="Providers" ThisKey="OrgCode" OtherKey="OrgCode" Type="Provider" />
      <Association Name="Ministry_Organization" Member="Ministry" ThisKey="MinistryCode" OtherKey="MinistryCode" Type="Ministry" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Provider" Member="Providers">
    <Type Name="Provider">
      <Column Name="ProviderCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderName" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="OrgCode" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Association Name="Organization_Provider" Member="Organization" ThisKey="OrgCode" OtherKey="OrgCode" Type="Organization" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Service" Member="Services">
    <Type Name="Service">
      <Column Name="SVCCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SVCName" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="SVCDesc" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="ICF_Code" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="ProviderCode" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="StaffRole" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="SVCType" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="SVCObjective" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="SVCSupport" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="SVCStart" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="SVCEnd" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="ChildType" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ProblemToSolve" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrgAssignedCode" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceChildTypeMapping" Member="ServiceChildTypeMappings">
    <Type Name="ServiceChildTypeMapping">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SVCCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubWelfareID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SubActivity" Member="SubActivities">
    <Type Name="SubActivity">
      <Column Name="SACTCode" Type="System.String" DbType="Char(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SACTDesc" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="ACTCode" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="ICF_Code" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Association Name="Activity_SubActivity" Member="Activity" ThisKey="ACTCode" OtherKey="ACTCode" Type="Activity" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.SVCObjectiveDesc" Member="SVCObjectiveDescs">
    <Type Name="SVCObjectiveDesc">
      <Column Name="SVCObjectiveCode" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SVCObjectiveDescription" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SVCSupportDesc" Member="SVCSupportDescs">
    <Type Name="SVCSupportDesc">
      <Column Name="SVCSupportCode" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SVCSupportDescription" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SVCTypeDesc" Member="SVCTypeDescs">
    <Type Name="SVCTypeDesc">
      <Column Name="SVCTypeCode" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SVCTypeDescription" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>